/*
 * Runs automatically on Vercel during `npm run build` (see package.json and
 * vercel.json). This project has no bundler/framework, so this is the only
 * way to get values from Vercel's Environment Variables settings into
 * client-side JS: we read them here, at build time, on the server, and
 * write them into a small generated file that index.html loads as a plain
 * <script> tag before anything else runs.
 *
 * Do not put secret/service-role keys here — this file ends up shipped to
 * every visitor's browser. Only SUPABASE_URL and the public SUPABASE_ANON_KEY
 * belong here, same as they would in any client-side Supabase integration.
 */
const fs = require("fs");
const path = require("path");

const SUPABASE_URL = process.env.SUPABASE_URL || "";
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || "";

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn(
    "[build-env] SUPABASE_URL and/or SUPABASE_ANON_KEY are not set.\n" +
    "[build-env] The deployed site will show a submission error until these " +
    "are added in Vercel Project Settings -> Environment Variables and the " +
    "project is redeployed."
  );
}

const output =
  "// AUTO-GENERATED by scripts/build-env.js during `npm run build`.\n" +
  "// Do not edit this file by hand -- it is overwritten on every build,\n" +
  "// using the SUPABASE_URL / SUPABASE_ANON_KEY environment variables.\n" +
  "window.__ENV__ = {\n" +
  "  SUPABASE_URL: " + JSON.stringify(SUPABASE_URL) + ",\n" +
  "  SUPABASE_ANON_KEY: " + JSON.stringify(SUPABASE_ANON_KEY) + "\n" +
  "};\n";

fs.writeFileSync(path.join(__dirname, "..", "env-config.js"), output);
console.log("[build-env] Wrote env-config.js");
